import numpy as np


def preprocess_distance_matrix(distance_matrix):
    """
    Replace infeasible distances (100000) with np.inf to prevent invalid calculations.

    Parameters:
        - distance_matrix (numpy.ndarray): The original distance matrix.

    Returns:
        - numpy.ndarray: The modified distance matrix.
    """
    distance_matrix = np.where(distance_matrix == 100000, np.inf, distance_matrix)
    return distance_matrix


def calculate_fitness(route, distance_matrix):
    """
    Calculate total distance traveled by the car. Penalizes infeasible routes.

    Parameters:
        - route (list): A list representing the order of nodes visited in the route.
        - distance_matrix (numpy.ndarray): A matrix of the distances between nodes.

    Returns:
        - float: The negative total distance traveled (negative because we want to minimize distance).
                 Returns a large penalty if the route is infeasible.
    """
    total_distance = 0
    num_nodes = len(route)

    for i in range(num_nodes - 1):
        distance = distance_matrix[route[i], route[i + 1]]
        if np.isinf(distance):  # Infeasible route
            return -1e5  # Large penalty

        total_distance += distance

    # Add return distance
    last_leg = distance_matrix[route[-1], route[0]]
    if np.isinf(last_leg):
        return -1e5  # Large penalty

    total_distance += last_leg

    return -total_distance  # Negative because we minimize distance


def select_in_tournament(population, scores, number_tournaments=4, tournament_size=3):
    """
    Tournament selection for genetic algorithm.

    Parameters:
        - population (list): The current population of routes.
        - scores (np.array): The fitness scores corresponding to each individual.
        - number_tournaments (int): Number of tournaments to run.
        - tournament_size (int): Number of individuals in each tournament.

    Returns:
        - list: A list of selected individuals for crossover.
    """
    selected = []
    
    for _ in range(number_tournaments):
        idx = np.random.choice(len(population), tournament_size, replace=True)  # Allow replacement
        best_idx = idx[np.argmin(scores[idx])]  # Select the individual with the best (lowest) score
        selected.append(population[best_idx])
    
    return selected


def order_crossover(parent1, parent2):
    """
    Order crossover (OX) for permutations.

    Parameters:
        - parent1 (list): The first parent route.
        - parent2 (list): The second parent route.

    Returns:
        - list: The offspring route generated by the crossover.
    """
    size = len(parent1)
    start, end = sorted(np.random.choice(range(size), 2, replace=False))
    offspring = [None] * size
    offspring[start:end + 1] = parent1[start:end + 1]
    fill_values = [x for x in parent2 if x not in offspring[start:end + 1]]
    idx = 0
    for i in range(size):
        if offspring[i] is None:
            offspring[i] = fill_values[idx]
            idx += 1
    return offspring


def mutate(route,
           mutation_rate = 0.1):
    """
    Mutation operator: swap two nodes in the route.

    Parameters:
        - route (list): The route to mutate.
        - mutation_rate (float): The chance to mutate an individual.
    Returns:
        - list: The mutated route.
    """
    if np.random.rand() < mutation_rate:
        i, j = np.random.choice(len(route), 2, replace=False)
        route[i], route[j] = route[j], route[i]
    return route

def generate_unique_population(population_size, num_nodes):
    """
    Generate a unique population of individuals for a genetic algorithm.

    Each individual in the population represents a route in a graph, where the first node is fixed (0) and the 
    remaining nodes are a permutation of the other nodes in the graph. This function ensures that all individuals
    in the population are unique.

    Parameters:
        - population_size (int): The desired size of the population.
        - num_nodes (int): The number of nodes in the graph, including the starting node.

    Returns:
        - list of lists: A list of unique individuals, where each individual is represented as a list of node indices.
    """
    population = set()
    while len(population) < population_size:
        individual = [0] + list(np.random.permutation(np.arange(1, num_nodes)))
        population.add(tuple(individual))
    return [list(ind) for ind in population]
